version: '3'

services:
  backend:
    container_name: backend
    image: lucasvazelle/finance_projet_sentiment_analyse-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - frontend
    environment:
      - ENV=production

  frontend:
    container_name: frontend
    image: lucasvazelle/finance_projet_sentiment_analyse-frontend
    command: streamlit run app/frontend_docker.py
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
